import Head from 'next/head';
import { Button } from '../components/button';
import { Hero } from '@/sections/home/hero';
import { SearchResults } from '@/sections/home/search-results';
import { Container } from '@/components/container';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container>
                    <Hero />
                    <SearchResults />
                </Container>
            </main>
        </>
    );
}
